---
language: php

php:
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

notifications:
    email: false

branches:
    only:
        - develop

before_install:
    - composer self-update
    - composer install --prefer-dist

script:
    - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then php app/task build; else php vendor/bin/phpunit -c app/build; fi;

after_script:
    - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then php vendor/bin/coveralls; fi;
