#!/usr/bin/env php
<?php
/**
 * This file is part of the Novuso Framework
 *
 * @copyright Copyright (c) 2015, Novuso. <http://novuso.com>
 * @license   http://opensource.org/licenses/MIT The MIT License
 * @author    John Nickell <email@johnnickell.com>
 */

set_time_limit(0);

require __DIR__.'/autoload.php';

$paths = require __DIR__.'/paths.php';
$robo = $paths['bin'].'/robo';

if (!file_exists($robo)) {
    $message = sprintf('Composer installation required; missing %s', $robo);
    throw new RuntimeException($message);
}

chdir(__DIR__);

require $robo;
