#==============================================================================
# Use the following to tag command filter services:
#
# tags:
#     - { name: novuso_common.command_filter }
#==============================================================================
# Use the following to tag command handler services:
#
# tags:
#     -
#         name: novuso_common.command_handler
#         command: My\Example\App\RegisterUserCommand
#==============================================================================
# Use the following to tag subscriber services:
#
# tags:
#     - { name: novuso_common.event_subscriber }
#==============================================================================
parameters:
    # List of Novuso\Common\Application\Command\Filter instances
    novuso_common.command_filters: []
    # Map of ['handler_service_id' => 'Command\\Class']
    novuso_common.command_handlers: []
services:
    # Novuso\Common\Application\Service\Container
    novuso_common.service_container:
        class: Novuso\Common\Adapter\Infrastructure\Service\SymfonyContainer
        arguments:
            - @service_container

    # Novuso\Common\Application\Logging\Logger
    novuso_common.logger:
        class: Novuso\Common\Adapter\Infrastructure\Logging\PsrLogger
        arguments:
            - @logger

    # Novuso\Common\Domain\Event\Dispatcher
    novuso_common.event_dispatcher:
        class: Novuso\Common\Application\DomainEvent\Dispatcher\ServiceAwareDispatcher
        arguments:
            - @novuso_common.service_container

    # Novuso\Common\Application\Command\CommandBus
    novuso_common.command_bus:
        class: Novuso\Common\Application\Command\Pipeline\CommandPipeline
        arguments:
            - @novuso_common.application_bus
            - %novuso_common.command_filters%

    # Novuso\Common\Application\Command\Resolver\ServiceMap
    novuso_common.command_resolver.service_map:
        class: Novuso\Common\Application\Command\Resolver\ServiceMap
        arguments:
            - @novuso_common.service_container
            - %novuso_common.command_handlers%

    novuso_common.application_bus:
        class: Novuso\Common\Application\Command\Pipeline\ApplicationBus
        arguments:
            - @novuso_common.command_resolver
        public: false

    novuso_common.command_resolver:
        class: Novuso\Common\Application\Command\Resolver\ServiceResolver
        arguments:
            - @novuso_common.command_resolver.service_map
        public: false
