#==============================================================================
# Use the following to tag command filter services:
# tags:
#     - { name: novuso_common.command_filter }
#==============================================================================
# Use the following to tag query filter services:
# tags:
#     - { name: novuso_common.query_filter }
#==============================================================================
# Use the following to tag command handler services:
# tags:
#     -
#         name: novuso_common.command_handler
#         command: Namespace\CommandClassName
#==============================================================================
# Use the following to tag query handler services:
# tags:
#     -
#         name: novuso_common.query_handler
#         query: Namespace\QueryClassName
#==============================================================================
# Use the following to tag domain event subscriber services:
# tags:
#     - { name: novuso_common.event_subscriber }
#==============================================================================
# Use the following to tag HTTP responder services:
# tags:
#     -
#         name: novuso_common.responder
#         action: Namespace\ActionClassName
#==============================================================================
services:
    # Novuso\Common\Application\Container\Container
    novuso_common.service_container:
        class: Novuso\Common\Adapter\Infrastructure\Container\SymfonyContainer
        arguments:
            - @service_container
    # Novuso\Common\Application\Logging\Logger
    novuso_common.logger:
        class: Novuso\Common\Adapter\Infrastructure\Logging\PsrLogger
        arguments:
            - @logger
    # Novuso\Common\Application\Messaging\Event\Dispatcher
    novuso_common.event_dispatcher:
        class: Novuso\Common\Application\Messaging\Event\EventServiceDispatcher
        arguments:
            - @novuso_common.service_container
    # Novuso\Common\Application\Messaging\Command\CommandBus
    novuso_common.command_bus:
        class: Novuso\Common\Application\Messaging\Command\CommandPipeline
        arguments:
            - @novuso_common.command_handler_bus
    # Novuso\Common\Application\Messaging\Query\QueryService
    novuso_common.query_service:
        class: Novuso\Common\Application\Messaging\Query\QueryPipeline
        arguments:
            - @novuso_common.query_handler_service

    novuso_common.command_handler_bus:
        class: Novuso\Common\Application\Messaging\Command\CommandHandlerBus
        arguments:
            - @novuso_common.command_service_resolver
        public: false
    novuso_common.command_service_resolver:
        class: Novuso\Common\Application\Messaging\Command\Resolver\CommandServiceResolver
        arguments:
            - @novuso_common.command_service_map
        public: false
    novuso_common.command_service_map:
        class: Novuso\Common\Application\Messaging\Command\Resolver\CommandServiceMap
        arguments:
            - @novuso_common.service_container
    novuso_common.query_handler_service:
        class: Novuso\Common\Application\Messaging\Query\QueryHandlerService
        arguments:
            - @novuso_common.query_service_resolver
        public: false
    novuso_common.query_service_resolver:
        class: Novuso\Common\Application\Messaging\Query\Resolver\QueryServiceResolver
        arguments:
            - @novuso_common.query_service_map
        public: false
    novuso_common.query_service_map:
        class: Novuso\Common\Application\Messaging\Query\Resolver\QueryServiceMap
        arguments:
            - @novuso_common.service_container
    novuso_common.responder_subscriber:
        class: Novuso\Common\Adapter\Presentation\Symfony\Http\Subscriber\ResponderSubscriber
        arguments:
            - @novuso_common.responder_service_resolver
        tags:
            - { name: kernel.event_subscriber }
    novuso_common.responder_service_resolver:
        class: Novuso\Common\Adapter\Presentation\Symfony\Http\Resolver\ResponderServiceResolver
        arguments:
            - @novuso_common.responder_service_map
        public: false
    novuso_common.responder_service_map:
        class: Novuso\Common\Adapter\Presentation\Symfony\Http\Resolver\ResponderServiceMap
        arguments:
            - @novuso_common.service_container
