#
# Use the following to tag command middleware services:
#
# tags:
#     - { name: novuso_common.command_middleware }
#
#==============================================================================
#
# Use the following to tag command handler services:
#
# tags:
#     -
#         name: novuso_common.command_handler
#         command: My\Example\App\RegisterUserCommand
#
#==============================================================================
services:
    # Novuso\Common\Application\Command\CommandBus
    novuso_common.command.command_bus:
        alias: novuso_common.command.pipeline.command_pipeline
    # Novuso\Common\Application\Command\Resolver\HandlerResolver
    novuso_common.command.resolver:
        alias: novuso_common.command.resolver.service_resolver
    # Novuso\Common\Application\Command\Resolver\ServiceMap
    novuso_common.command.resolver.service_map:
        class: Novuso\Common\Application\Command\Resolver\ServiceMap
        arguments:
            - @novuso_common.service.container
    novuso_common.command.pipeline.command_pipeline:
        class: Novuso\Common\Application\Command\Pipeline\CommandPipeline
        arguments:
            - @novuso_common.command.pipeline.application_bus
    novuso_common.command.pipeline.application_bus:
        class: Novuso\Common\Application\Command\Pipeline\ApplicationBus
        arguments:
            - @novuso_common.command.resolver
    novuso_common.command.pipeline.command_logger:
        class: Novuso\Common\Application\Command\Pipeline\CommandLogger
        arguments:
            - @novuso_common.logging.logger
        tags:
            - { name: novuso_common.command_middleware }
    novuso_common.command.resolver.service_resolver:
        class: Novuso\Common\Application\Command\Resolver\ServiceResolver
        arguments:
            - @novuso_common.command.resolver.service_map
